# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12b33909f37a5dfd2b1c1e0bd688d8e37fb4dbbfadcba96622ab98ad12bc7aaeeca3e4127ba42dd3e2dc64dde68a0a2b12c8580aaadaffd1a83c0dbd2054e3dd

test:
  secret_key_base: 597804534f79440e348614d5bc5cfb14383157e945a9d8185e8fdc65ba4b6740e80030e9fe23a6b33ede647f87219659afdb0ed1172ecbed1c669739763d97d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
